### ISSUE TITLE
Unexpected 'is-animating' pages when turning page right after init

### ISSUE THREAD

**Issue by benjaminlong** [djgrant/heidelberg#10]
First of all, thank you for your awesome work !

I discovered a tiny bug.
If you programmatically turning a page right after init like this:

```javascript
var book1 = new Heidelberg($('#Heidelberg-example-1'), {
  previousButton: $('#previous'),
  nextButton: $('#next'),
  hasSpreads: true,
  onPageTurn: function(el, els) {
    console.log('Page turned');
  },
  onSpreadSetup: function(el) {
    console.log('Spread setup');
  }
});

book1.turnPage(5);
```

Page 5 is active, but `webkitTransitionEnd oTransitionEnd msTransitionEnd transitionend` events wont be triggered - See file heidelberg.js line 207
```javascript
els.pagesAnimating.on('webkitTransitionEnd oTransitionEnd msTransitionEnd transitionend', function () {
  els.pagesAnimating.removeClass('is-animating');
  els.pagesActive.removeClass('was-active');
}.bind(document));
```
and you will have unexpected 'is-animating' pages.

<img width="447" alt="screen shot 2016-12-07 at 11 23 16 am" src="https://cloud.githubusercontent.com/assets/913526/20964305/3d6cbc38-bc71-11e6-9c99-6f4fb1155729.png">

As a result, if you keep turning the pages 'forward', the left page will stay the same.
My goal was to init the book and open it at a given page. I guess, It could be done directly by adding an option to Heidelberg and update the code around line 80-88. But I am not sure it's a wanted behavior.

```javascript
if(!options.canClose) {
  var coverEl = $('<div />').addClass('Heidelberg-HiddenCover');
  el.prepend(coverEl.clone());
  el.append(coverEl.clone());
  els.pages.eq(0).add(els.pages.eq(1)).addClass('is-active');
}
else {
  els.pages.eq(0).addClass('is-active');
}
```

I was hoping to come with a pull request to fix this, but I don't have it yet. I was hoping to have some feedbacks and advices from you.

All the best !

**Comment by benjaminlong** [comment]
Adding an "index" options could result to something like:
https://github.com/benjaminlong/heidelberg/commit/12801e857bd06ee12ffda6c50f2d17ac557d0421

**Comment by djgrant** [comment]
Thanks for the bug report @benjaminlong. I like your solution. Adding an `initialActivePage` parameter to the options block seems like a sensible idea to me. Feel free to submit a PR for this!
