### ISSUE TITLE
Image is having "dark areas" when chrome has page zoom between 100 and 200% 

### ISSUE THREAD

**Issue by phackwer** [djgrant/heidelberg#14]
Image having "dark areas" when chrome has page zoom between 100 and 200% and you paginate. 

If you are in 100%, or 200%, that doesn't happen. 

A number of people report similar problems with chrome, but seems like the solution required to fix it is already applied to the code:

https://www.google.ie/search?q=chrome+image+rendering+problem+on+transition&oq=chrome+image+rendering+problem+on+transition&aqs=chrome..69i57.8566j0j7&sourceid=chrome&ie=UTF-8

  -webkit-backface-visibility: hidden;
  -webkit-transform: rotate(0);
  -moz-transform: rotate(0);
  transform: rotate(0);

Is there any other way to avoid this problem?

I've made this video to make it clearer on the issues we have:

https://youtu.be/uDZ6fypNlRY

Thanks

**Comment by djgrant** [comment]
In my experience CSS transforms don't work as well when images are resized, or, as in your case the whole browser window is zoomed. 

I haven't updated this project in a long while. I think the CSS is still used for https://www.wonderbly.com/. You can try poking around there and seeing if your problem exists there and if any additional styles being used that might help you.

**Comment by phackwer** [comment]
Just tried, that code is crazy. :-) They minifyed all the code, impossible to read now. :-/ Thanks anyway.

**Comment by phackwer** [comment]
Hey, the problem is not the image. :-) Turns out it's related to the overflow. Probably because of the resizing, chrome tries to also resize the scrollbars, that are "hidden", but are, logically, in there (the renderer don't forget about them). I've tried to change the overflow for all other possible values and had all kind of different results. I will check that later. Anyway, thanks for your attention.

**Comment by djgrant** [comment]
Interesting. Feel free to raise a PR if you have a fix.

**Comment by phackwer** [comment]
Just remove the background colors and it's solved. :-)

**Comment by hercipri** [comment]
@djgrant, I am interested in building a page similar to wonderbly.com. Can you give me (and under what conditions, possibly the price) the code of the page?
