### ISSUE TITLE
Integration Type Script, requireJS Angular2

### ISSUE THREAD

**Issue by mpoiriert** [djgrant/heidelberg#9]
Hi,

I am trying to integrate your library in a Angular2 project. I am using npm, webpack and typescript. I am pretty new to all of this and I am not able to do so.

If you are not familiar with Angular2 I don't think it's a issue just a how to in TypeScript/RequireJS would be enough for me to manage.

Thanks !

**Comment by callumacrae** [comment]
For requiring the library, see "Loading modules from CommonJS packages here": http://requirejs.org/docs/commonjs.html#packages

For using the library, set up a heidelberg / book directive and call this library from the link function.
